### ISSUE TITLE
Exception - A propriedade "BrPack\Field\Card.autocomplete" não está definida.

### ISSUE THREAD

**Issue by goulartfs** [igorsantos07/yii-br-pack#3]
After updating Yii version from 1.1.14 to 1.1.17, the framework now throws this exception:
"exception 'CException' with message 'A propriedade "BrPack\Field\Card.autocomplete" não está definida.'"

**Comment by rtancman** [comment]
+1 ta bugado na versão 5.6

**Comment by ashton** [comment]
+1 seduzente <3

**Comment by chevectra87** [comment]
+1

**Comment by goulartfs** [comment]
Pintou um clima que eu vi!

**Comment by chevectra87** [comment]
VC TC DE ONDE?

**Comment by igorsantos07** [comment]
como tu quer que eu debugue algo sem um stacktrace? não sei de onde veio esse campo de autocomplete...
nao tenho projeto mais pra testar isso nem uso há anos... colabora aí rs
tu nao é o cara do xdebug?

**Comment by goulartfs** [comment]
RJ e vc?

**Comment by rtancman** [comment]
alguma mina de VG aê querendo TC?

**Comment by chevectra87** [comment]
Guadalupe na área?

**Comment by goulartfs** [comment]
Partiu praia fds?

**Comment by goulartfs** [comment]
Amigo Igor, aqui o Stack:

Stack trace:
#0 /projeto/vendor/yiisoft/yii/framework/web/CWidgetFactory.php(161): CComponent->__set('autocomplete', 'off')
#1 /projeto/vendor/yiisoft/yii/framework/web/CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'BrPack\Field\Ca...', Array)
#2 /projeto/vendor/yiisoft/yii/framework/web/CBaseController.php(180): CBaseController->createWidget('BrPack\Field\Ca...', Array)
#3 /projeto/app/views/site/index.php(112): CBaseController->widget('BrPack\Field\Ca...', Array)
#4 /projeto/vendor/yiisoft/yii/framework/web/CBaseController.php(126): require('/home/fsynthis/...')
#5 /projeto/vendor/yiisoft/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/home/fsynthis/...', Array, true)
#6 /projeto/vendor/yiisoft/yii/framework/web/CController.php(869): CBaseController->renderFile('/home/fsynthis/...', Array, true)
#7 /projeto/vendor/yiisoft/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#8 /projeto/app/controllers/SiteController.php(63): CController->render('index', Array)
#9 /projeto/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#10 /projeto/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /projeto/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 /projeto/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#13 /projeto/vendor/yiisoft/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 /projeto/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 /projeto/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 /projeto/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()
#17 /projeto/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /projeto/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('')
#19 /projeto/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#20 /projeto/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#21 /projeto/web/index.php(16): CApplication->run()
#22 {main}
REQUEST_URI=/

**Comment by rtancman** [comment]
+++ hhvm

**Comment by igorsantos07** [comment]
Cara, realmente não sei o que tá rolando não. Chutaria que o modo do Yii lidar com atributos extras do HTML mudou entre essas versões. Dá uma olhada em como o `CMaskedField` funciona e vê como ele se comportaria pra você por autocomplete=off nele, ou algo parecido - visto que o `Field\Card` extende dele.

**Comment by igorsantos07** [comment]
O campo de `autocomplete` deveria estar dentro do `htmlOptions`, e não lançado diretamente nas props do componente.
